global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'fraud-detection-api'
    static_configs:
      - targets: ['fraud-detection-api:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
